### ISSUE TITLE
timespec_normalise incorrect according to posix

### ISSUE THREAD

**Issue by nico** [solemnwarning/timespec#4]
Hi, I found this repo while looking something up. I found a small bug: https://pubs.opengroup.org/onlinepubs/007908799/xsh/realtime.html says "The tv_nsec member is only valid if greater than or equal to zero, and less than the number of nanoseconds in a second (1000 million)". So {0, -500000000} should be normalized to {-1, 500000000}.

**Comment by solemnwarning** [comment]
It took me a while to get around to this, but thanks for reporting it!
